<?php

/**
 * MIT License. This file is part of the Propel package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Propel\Generator\Platform;

use Propel\Generator\Exception\EngineException;
use Propel\Generator\Model\Column;
use Propel\Generator\Model\Database;
use Propel\Generator\Model\Diff\ColumnDiff;
use Propel\Generator\Model\Diff\TableDiff;
use Propel\Generator\Model\Domain;
use Propel\Generator\Model\ForeignKey;
use Propel\Generator\Model\IdMethod;
use Propel\Generator\Model\Index;
use Propel\Generator\Model\PropelTypes;
use Propel\Generator\Model\Table;
use Propel\Generator\Model\Unique;
use Propel\Runtime\Exception\PropelException;

/**
 * Postgresql PlatformInterface implementation.
 *
 * @author Hans Lellelid <hans@xmpl.org> (Propel)
 * @author Martin Poeschl <mpoeschl@marmot.at> (Torque)
 * @author Niklas Närhinen <niklas@narhinen.net>
 */
class PgsqlPlatform extends DefaultPlatform
{
    /**
     * @var string
     */
    protected $createOrDropSequences = '';

    /**
     * Initializes db specific domain mapping.
     *
     * @return void
     */
    protected function initialize(): void
    {
        parent::initialize();
        $this->setSchemaDomainMapping(new Domain(PropelTypes::BOOLEAN, 'BOOLEAN'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::TINYINT, 'INT2'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::SMALLINT, 'INT2'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::BIGINT, 'INT8'));
        //$this->setSchemaDomainMapping(new Domain(PropelTypes::REAL, 'FLOAT'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::DOUBLE, 'DOUBLE PRECISION'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::FLOAT, 'DOUBLE PRECISION'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::LONGVARCHAR, 'TEXT'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::BINARY, 'BYTEA'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::VARBINARY, 'BYTEA'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::LONGVARBINARY, 'BYTEA'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::BLOB, 'BYTEA'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::CLOB, 'TEXT'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::OBJECT, 'BYTEA'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::PHP_ARRAY, 'TEXT'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::ENUM, 'INT2'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::SET, 'INT4'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::DECIMAL, 'NUMERIC'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::DATETIME, 'TIMESTAMP'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::UUID, 'uuid'));
        $this->setSchemaDomainMapping(new Domain(PropelTypes::UUID_BINARY, 'BYTEA'));
    }

    /**
     * @return string
     */
    public function getNativeIdMethod(): string
    {
        return IdMethod::SEQUENCE;
    }

    /**
     * @return string
     */
    public function getAutoIncrement(): string
    {
        return '';
    }

    /**
     * Process all known auto-increment types.
     * 
     * 3 ai types:
     * 1: sequence - id integer default nextval('my_seq') - manual sequence
     * 2: serial   - id serial - no sequence
     * 3: identity - id integer generated by default/always as identity - no sequence
     * 
     * @return string
     */
    public function getAutoIncrementClause(string $idMethod): ?string{
        switch(strtolower($idMethod)){
            case IdMethod::IDENTITY:
            case IdMethod::NATIVE:
            case IdMethod::SEQUENCE:
            case IdMethod::SERIAL:
                return '';
        }
        return null;
    }

    /**
     * @return array<int>
     */
    public function getDefaultTypeSizes(): array
    {
        return [
            'char' => 1,
            'character' => 1,
            'integer' => 32,
            'bigint' => 64,
            'smallint' => 16,
            'double precision' => 54,
        ];
    }

    /**
     * @return int
     */
    public function getMaxColumnNameLength(): int
    {
        return 63;
    }

    /**
     * @param mixed $value
     *
     * @return string
     */
    public function getBooleanString($value): string
    {
        // parent method does the checking for allows string
        // representations & returns integer
        $value = parent::getBooleanString($value);

        return ($value ? "'t'" : "'f'");
    }

    /**
     * @return bool
     */
    public function supportsNativeDeleteTrigger(): bool
    {
        return true;
    }

    /**
     * Override to provide sequence names that conform to postgres' standard when
     * no id-method-parameter specified.
     *
     * @param \Propel\Generator\Model\Table $table
     *
     * @return string|null
     */
    public function getSequenceName(Table $table): ?string
    {
        if ($table->getIdMethod() !== IdMethod::NATIVE) {
            return null;
        }
        $idMethodParams = $table->getIdMethodParameters();
        if ($idMethodParams) {
            return $idMethodParams[0]->getValue();
        }
        // We're going to ignore a check for max length (mainly
        // because I'm not sure how Postgres would handle this w/ SERIAL anyway)
        foreach ($table->getColumns() as $col) {
            if (!$col->isAutoIncrement()) {
                continue;
            }
            // there's only one auto-increment column allowed
            return $this->getColumnSequenceName($col);
        }
        return null;
    }

    /**
     * @param \Propel\Generator\Model\Table $table
     *
     * @return string
     */
    protected function getAddSequenceDDL(Table $table): string
    {
        $tableSequence = $this->getSequenceName($table);
        if (!$tableSequence) {
            return '';
        }
        
        return sprintf(
            "\nCREATE SEQUENCE IF NOT EXISTS %s;\n",
            $this->quoteIdentifier(strtolower($tableSequence)),
        );
    }

    /**
     * @param \Propel\Generator\Model\Table $table
     *
     * @return string
     */
    protected function getDropSequenceDDL(Table $table): string
    {
        $tableSequence = $this->getSequenceName($table);
        if (!$tableSequence) {
            return '';
        }
        $pattern = "\nDROP SEQUENCE %s;\n";
        return sprintf(
            $pattern,
            $this->quoteIdentifier(strtolower($tableSequence)),
        );
    }

    /**
     * @param \Propel\Generator\Model\Database $database
     *
     * @return string
     */
    public function getAddSchemasDDL(Database $database): string
    {
        $ret = '';
        $schemas = [];
        foreach ($database->getTables() as $table) {
            $vi = $table->getVendorInfoForType('pgsql');
            if ($vi->hasParameter('schema') && !isset($schemas[$vi->getParameter('schema')])) {
                $schemas[$vi->getParameter('schema')] = true;
                $ret .= $this->getAddSchemaDDL($table);
            }
        }

        return $ret;
    }

    /**
     * @param \Propel\Generator\Model\Table $table
     *
     * @return string
     */
    public function getAddSchemaDDL(Table $table): string
    {
        $vi = $table->getVendorInfoForType('pgsql');
        if ($vi->hasParameter('schema')) {
            $pattern = "\nCREATE SCHEMA %s;\n";

            return sprintf($pattern, $this->quoteIdentifier($vi->getParameter('schema')));
        }

        return '';
    }

    /**
     * @param \Propel\Generator\Model\Table $table
     *
     * @return string
     */
    public function getUseSchemaDDL(Table $table): string
    {
        $vi = $table->getVendorInfoForType('pgsql');
        if ($vi->hasParameter('schema')) {
            $pattern = "\nSET search_path TO %s;\n";

            return sprintf($pattern, $this->quoteIdentifier($vi->getParameter('schema')));
        }

        return '';
    }

    /**
     * @param \Propel\Generator\Model\Table $table
     *
     * @return string
     */
    public function getResetSchemaDDL(Table $table): string
    {
        $vi = $table->getVendorInfoForType('pgsql');
        if ($vi->hasParameter('schema')) {
            return "\nSET search_path TO public;\n";
        }

        return '';
    }

    /**
     * @param \Propel\Generator\Model\Database $database
     *
     * @return string
     */
    public function getAddTablesDDL(Database $database): string
    {// check with DefaultPlatform
        $ret = $this->getAddSchemasDDL($database);

        foreach ($database->getTablesForSql() as $table) {
            $this->normalizeTable($table);
        }

        foreach ($database->getTablesForSql() as $table) {
            $ret .= $this->getCommentBlockDDL($table->getName());
            $ret .= $this->getDropTableDDL($table);
            $ret .= $this->getAddTableDDL($table);
            $ret .= $this->getAddIndicesDDL($table);
        }
        foreach ($database->getTablesForSql() as $table) {
            $ret .= $this->getAddForeignKeysDDL($table);
        }

        if ($ret) {
            $ret = $this->getBeginDDL() . $ret . $this->getEndDDL();
        }

        return $ret;
    }

    /**
     * @param \Propel\Generator\Model\ForeignKey $fk
     *
     * @return string
     */
    public function getForeignKeyDDL(ForeignKey $fk): string
    {
        $script = parent::getForeignKeyDDL($fk);

        $pgVendorInfo = $fk->getVendorInfoForType('pgsql');
        if (filter_var($pgVendorInfo->getParameter('deferrable'), FILTER_VALIDATE_BOOLEAN)) {
            $script .= ' DEFERRABLE';
            if (filter_var($pgVendorInfo->getParameter('initiallyDeferred'), FILTER_VALIDATE_BOOLEAN)) {
                $script .= ' INITIALLY DEFERRED';
            }
        }

        return $script;
    }

    /**
     * @return string
     */
    public function getBeginDDL(): string
    {
        return "\nBEGIN;\n";
    }

    /**
     * @return string
     */
    public function getEndDDL(): string
    {
        return "\nCOMMIT;\n";
    }

    /**
     * @param \Propel\Generator\Model\Table $table
     *
     * @return string
     */
    public function getAddTableDDL(Table $table): string
    {
        $ret = '';
        $ret .= $this->getUseSchemaDDL($table);
        $ret .= $this->getAddSequenceDDL($table);

        $lines = [];

        foreach ($table->getColumns() as $column) {
            $lines[] = $this->getColumnDDL($column);
        }

        if ($table->hasPrimaryKey()) {
            $lines[] = $this->getPrimaryKeyDDL($table);
        }

        foreach ($table->getUnices() as $unique) {
            $lines[] = $this->getUniqueDDL($unique);
        }

        $sep = ",\n    ";
        $pattern = "\nCREATE TABLE %s\n(    %s\n);\n";
        $ret .= sprintf(
            $pattern,
            $this->quoteIdentifier($table->getName()),
            implode($sep, $lines),
        );

        if ($table->hasDescription()) {
            $pattern = "\nCOMMENT ON TABLE %s IS %s;\n";
            $ret .= sprintf(
                $pattern,
                $this->quoteIdentifier($table->getName()),
                $this->quote($table->getDescription()),
            );
        }

        $ret .= $this->getAddColumnsComments($table);
        $ret .= $this->getResetSchemaDDL($table);

        return $ret;
    }

    /**
     * @param \Propel\Generator\Model\Table $table
     *
     * @return string
     */
    protected function getAddColumnsComments(Table $table): string
    {
        $ret = '';
        foreach ($table->getColumns() as $column) {
            $ret .= $this->getAddColumnComment($column);
        }

        return $ret;
    }

    /**
     * @param \Propel\Generator\Model\Column $column
     *
     * @return string
     */
    protected function getAddColumnComment(Column $column): string
    {
        $description = $column->getDescription();
        if(!$description){
            return '';
        }
        $pattern = "\nCOMMENT ON COLUMN %s.%s IS %s;\n";
        return sprintf(
            $pattern,
            $this->quoteIdentifier($column->getTable()->getName()),
            $this->quoteIdentifier($column->getName()),
            $this->quote($description),
        );
    }

    /**
     * @param \Propel\Generator\Model\Table $table
     *
     * @return string
     */
    public function getDropTableDDL(Table $table): string
    {
        $ret = $this->getUseSchemaDDL($table);
        $pattern = "\nDROP TABLE IF EXISTS %s CASCADE;\n";
        $ret .= sprintf($pattern, $this->quoteIdentifier($table->getName()));
        $ret .= $this->getDropSequenceDDL($table);
        $ret .= $this->getResetSchemaDDL($table);

        return $ret;
    }

    protected function getColumnTypeDeclaration(Column $column): string
    {
        $sqlType = $column->getDomain()->getSqlType();
        $table = $column->getTable();

        // 
        if ($column->isAutoIncrement() && $table->getIdMethod() === IdMethod::SERIAL) {
            $sqlType = $column->getType() === PropelTypes::BIGINT ? 'bigserial' : 'serial';
        }


        $isNonNumericNumber = $this->isNumber($sqlType) && strtoupper($sqlType) !== 'NUMERIC';
        if (!$this->hasSize($sqlType) || !$column->isDefaultSqlType($this) || $isNonNumericNumber)
        {
            return $sqlType;
        }
        return $sqlType . $column->getSizeDefinition();
    }

    /**
     * @param \Propel\Generator\Model\Unique $unique
     *
     * @return string
     */
    public function getUniqueDDL(Unique $unique): string
    {
        return sprintf(
            'CONSTRAINT %s UNIQUE (%s)',
            $this->quoteIdentifier($unique->getName()),
            $this->getColumnListDDL($unique->getColumnObjects()),
        );
    }

    /**
     * @param string $fromTableName
     * @param string $toTableName
     *
     * @return string
     */
    public function getRenameTableDDL(string $fromTableName, string $toTableName): string
    {
        if (($pos = strpos($toTableName, '.')) !== false) {
            $toTableName = substr($toTableName, $pos + 1);
        }

        $pattern = "\nALTER TABLE %s RENAME TO %s;\n";

        return sprintf(
            $pattern,
            $this->quoteIdentifier($fromTableName),
            $this->quoteIdentifier($toTableName),
        );
    }

    /**
     * @see Platform::supportsSchemas()
     *
     * @return bool
     */
    public function supportsSchemas(): bool
    {
        return true;
    }

    /**
     * @param string $sqlType
     *
     * @return bool
     */
    public function hasSize(string $sqlType): bool
    {
        return !in_array(strtoupper($sqlType), ['BYTEA', 'TEXT', 'DOUBLE PRECISION'], true);
    }

    /**
     * @return bool
     */
    public function hasStreamBlobImpl(): bool
    {
        return true;
    }

    /**
     * @return bool
     */
    public function supportsVarcharWithoutSize(): bool
    {
        return true;
    }

    /**
     * @param \Propel\Generator\Model\Diff\TableDiff $tableDiff
     *
     * @return string
     */
    public function getModifyTableDDL(TableDiff $tableDiff): string
    {
        $ret = parent::getModifyTableDDL($tableDiff);

        if ($this->createOrDropSequences) {
            $ret = $this->createOrDropSequences . $ret;
        }

        $this->createOrDropSequences = '';

        return $ret;
    }

    /**
     * Overrides the implementation from DefaultPlatform
     *
     * @see DefaultPlatform::getModifyColumnDDL
     *
     * @param \Propel\Generator\Model\Diff\ColumnDiff $columnDiff
     *
     * @return string
     */
    public function getModifyColumnDDL(ColumnDiff $columnDiff): string
    {
        $alterTableStatements = [];
        $changedProperties = $columnDiff->getChangedProperties();

        $fromColumn = $columnDiff->getFromColumn();
        $toColumn = $columnDiff->getToColumn();

        // update column type
        if (
            isset($changedProperties['size']) || 
            isset($changedProperties['type']) || 
            isset($changedProperties['sqlType']) || 
            isset($changedProperties['scale'])
        ) {
            $columnDeclaration = 'TYPE ' . $this->getColumnTypeDeclaration($toColumn);
            
            $using = $this->getUsingCast($fromColumn, $toColumn);
            if ($using) {
                $columnDeclaration .= $using;
            }
            $alterTableStatements[] = $this->buildAlterColumnStatement($toColumn, $columnDeclaration);
        }

        // update auto increment
        $autoIncrementStatements = $this->getUpdateAutoIncrementStatements($fromColumn, $toColumn);
        if($autoIncrementStatements){
            array_push($alterTableStatements, ...$autoIncrementStatements);
            unset($changedProperties['defaultValueValue']);
        }

        // update default value
        if (isset($changedProperties['defaultValueValue'])) {
            [$oldValue, $newValue] = $changedProperties['defaultValueValue'];
            $isDrop = ($oldValue !== null && $newValue === null);
            $defaultValueStatement = $isDrop ?' DROP DEFAULT' : ' SET ' . $this->getColumnDefaultValueDDL($toColumn);

            $alterTableStatements[]= $this->buildAlterColumnStatement($toColumn, $defaultValueStatement);
        }

        // update not null
        if (isset($changedProperties['notNull'])) {
            $property = $changedProperties['notNull'];
            $notNull = ($property[1]) ? ' SET NOT NULL' : ' DROP NOT NULL';

            $alterTableStatements[] = $this->buildAlterColumnStatement($toColumn, $notNull);
        }

        return implode('', $alterTableStatements);
    }

    protected function buildAlterColumnStatement(Column $column, string $alterExpression){
        $columnName = $this->quoteIdentifier($column->getName());
        $tableName = $this->quoteIdentifier($column->getTable()->getName());

        return "\nALTER TABLE $tableName ALTER COLUMN $columnName $alterExpression;\n";
    }

    protected function getUpdateAutoIncrementStatements(Column $fromColumn, Column $toColumn): ?array
    {
        $fromIdMethod = $fromColumn->isAutoIncrement() ? $fromColumn->getTable()->getIdMethod() : null;
        $toIdMethod = $toColumn->isAutoIncrement() ? $toColumn->getTable()->getIdMethod() : null;

        if ($fromIdMethod === $toIdMethod){
            return null;
        }

        $statements = [];
        if($fromIdMethod){
            $dropExpression = $this->getDropAutoIncrementExpression($fromColumn);
            $statements[] = $this->buildAlterColumnStatement($fromColumn, $dropExpression);;
            if ($this->idMethodNeedsSequence($fromIdMethod)){
                $statements[] = $this->buildDropColumnSequenceStatement($fromColumn);
            }
        }

        if($toIdMethod){
            if ($this->idMethodNeedsSequence($toIdMethod)){
                $statements[] = $this->buildCreateColumnSequenceStatement($toColumn);
            }
            $autoIncrementExpression = $this->buildAutoIncrementDefaultValue($toColumn);
            if ($autoIncrementExpression) {
                $statements[] = $this->buildAlterColumnStatement($toColumn, $autoIncrementExpression);
            }
        }

        return $statements;
    }

    protected function getColumnSequenceName($column): string
    {
        $tableName = $column->getTable()->getName();
        $colPlainName = $column->getName();

        return "{$tableName}_{$colPlainName}_seq";
    }

    protected function buildCreateColumnSequenceStatement(Column $column): string
    {
        $sequenceName = $this->getColumnSequenceName($column);
        $create = "CREATE SEQUENCE IF NOT EXISTS $sequenceName;";

        $columnName = $this->quoteIdentifier($column->getName());
        $tableName = $this->quoteIdentifier($column->getTable()->getName());
        $setval = "SELECT setval('$sequenceName', x.max::bigint) FROM (SELECT max($columnName) AS max FROM $tableName) x;";
        
        return "\n$create\n$setval\n";
    }

    protected function buildDropColumnSequenceStatement(Column $column): string
    {
        $sequenceName = $this->getColumnSequenceName($column);

        return "\nDROP SEQUENCE IF EXISTS $sequenceName CASCADE;\n";
    }

    protected function buildAutoIncrementDefaultValue(Column $column): ?string
    {

        $idMethod = $column->getTable()->getIdMethod();
        switch($idMethod){
            case IdMethod::IDENTITY:
                return 'ADD GENERATED ALWAYS AS IDENTITY'; // for now no BY DEFAULT
            case IdMethod::NATIVE:
            case IdMethod::SEQUENCE:
                $seqName = $this->getColumnSequenceName($column);
                return "SET DEFAULT nextval('$seqName'::regclass)";
            case IdMethod::SERIAL:
            default:
                return null;
        }
    }

    protected function getDropAutoIncrementExpression(Column $column): string
    {
        $idMethod = $column->getTable()->getIdMethod();
        switch($idMethod){
            case IdMethod::IDENTITY:
                return 'DROP IDENTITY';
            case IdMethod::NATIVE:
            case IdMethod::SEQUENCE:
                return 'DROP DEFAULT';
            case IdMethod::SERIAL:
            default:
                throw new EngineException("Propel cannot drop auto increment of type `$idMethod`");
        }
    }

    protected function columnUsesSequenceBasedIdMethod(Column $column){
        $idMethod = $column->getTable()->getIdMethod();

        return $column->isAutoIncrement() && $this->idMethodNeedsSequence($idMethod);
    }


    protected function idMethodNeedsSequence(?string $idMethod){
        return in_array($idMethod, [IdMethod::NATIVE, IdMethod::SEQUENCE], true);
    }

    /**
     * @param string $type
     *
     * @return bool
     */
    public function isUuid(string $type): bool
    {
        $strings = ['UUID'];

        return in_array(strtoupper($type), $strings, true);
    }

    /**
     * @param string $type
     *
     * @return bool
     */
    public function isString(string $type): bool
    {
        $strings = ['VARCHAR'];

        return in_array(strtoupper($type), $strings, true);
    }

    /**
     * @param string $type
     *
     * @return bool
     */
    public function isNumber(string $type): bool
    {
        $numbers = ['INTEGER', 'INT4', 'INT2', 'NUMBER', 'NUMERIC', 'SMALLINT', 'BIGINT', 'DECIMAL', 'REAL', 'DOUBLE PRECISION', 'SERIAL', 'BIGSERIAL'];

        return in_array(strtoupper($type), $numbers, true);
    }

    /**
     * @param \Propel\Generator\Model\Column $fromColumn
     * @param \Propel\Generator\Model\Column $toColumn
     *
     * @return string
     */
    public function getUsingCast(Column $fromColumn, Column $toColumn): string
    {
        $fromSqlType = strtoupper($fromColumn->getDomain()->getSqlType());
        $toSqlType = strtoupper($toColumn->getDomain()->getSqlType());
        $name = $fromColumn->getName();

        if ($this->isString($fromSqlType) && $this->isNumber($toSqlType)) {
            //cast from string to int
            return "
   USING CASE WHEN trim($name) SIMILAR TO '[0-9]+'
        THEN CAST(trim($name) AS integer)
        ELSE NULL END";
        }

        if ($this->isNumber($fromSqlType) && $toSqlType === 'BYTEA') {
            return " USING decode(CAST($name as text), 'escape')";
        }

        if (
            ($this->isNumber($fromSqlType) && $this->isNumber($toSqlType)) ||
            ($this->isString($fromSqlType) && $this->isString($toSqlType)) ||
            ($this->isNumber($fromSqlType) && $this->isString($toSqlType)) ||
            ($this->isUuid($fromSqlType) && $this->isString($toSqlType))
        ) {
            // no cast necessary
            return '';
        }

        if ($this->isString($fromSqlType) && $this->isUuid($toSqlType)) {
            return " USING $name::uuid";
        }

        return ' USING NULL';
    }

    /**
     * Overrides the implementation from DefaultPlatform
     *
     * @author Niklas Närhinen <niklas@narhinen.net>
     *
     * @see DefaultPlatform::getModifyColumnsDDL
     *
     * @param array<\Propel\Generator\Model\Diff\ColumnDiff> $columnDiffs
     *
     * @return string
     */
    public function getModifyColumnsDDL(array $columnDiffs): string
    {
        $ret = '';
        foreach ($columnDiffs as $columnDiff) {
            $ret .= $this->getModifyColumnDDL($columnDiff);
        }

        return $ret;
    }

    /**
     * Overrides the implementation from DefaultPlatform
     *
     * @author Niklas Närhinen <niklas@narhinen.net>
     *
     * @see DefaultPlatform::getAddColumnsDLL
     *
     * @param array<\Propel\Generator\Model\Column> $columns
     *
     * @return string
     */
    public function getAddColumnsDDL(array $columns): string
    {
        $ret = '';
        foreach ($columns as $column) {
            $ret .= $this->getAddColumnDDL($column);
        }

        return $ret;
    }

    /**
     * Overrides the implementation from DefaultPlatform
     *
     * @author Niklas Närhinen <niklas@narhinen.net>
     *
     * @see DefaultPlatform::getDropIndexDDL
     *
     * @param \Propel\Generator\Model\Index $index
     *
     * @return string
     */
    public function getDropIndexDDL(Index $index): string
    {
        if ($index instanceof Unique) {
            $pattern = "\nALTER TABLE %s DROP CONSTRAINT %s;\n";

            return sprintf(
                $pattern,
                $this->quoteIdentifier($index->getTable()->getName()),
                $this->quoteIdentifier($index->getName()),
            );
        }

        return parent::getDropIndexDDL($index);
    }

    /**
     * Get the PHP snippet for getting a Pk from the database.
     * Warning: duplicates logic from PgsqlAdapter::getId().
     * Any code modification here must be ported there.
     *
     * @param string $columnValueMutator
     * @param string $connectionVariableName
     * @param string $sequenceName
     * @param string $tab
     * @param string|null $phpType
     *
     * @throws \Propel\Generator\Exception\EngineException
     *
     * @return array<string>|string|null
     */
    public function getIdentifierPhp(
        string $columnValueMutator,
        string $connectionVariableName = '$con',
        string $sequenceName = '',
        string $tab = '            ',
        ?string $phpType = null
    ) {
        if (!$sequenceName) {
            throw new EngineException('PostgreSQL needs a sequence name to fetch primary keys');
        }
        $snippet = "
\$dataFetcher = %s->query(\"SELECT nextval('%s')\");
%s = %s\$dataFetcher->fetchColumn();";
        $script = sprintf(
            $snippet,
            $connectionVariableName,
            $sequenceName,
            $columnValueMutator,
            $phpType ? '(' . $phpType . ') ' : '',
        );

        return preg_replace('/^/m', $tab, $script);
    }

    /**
     * @param \Propel\Generator\Model\Index $index
     *
     * @return string
     */
    public function getAddIndexDDL(Index $index): string
    {
        if (!$index->isUnique()) {
            return parent::getAddIndexDDL($index);
        }

        $pattern = "
ALTER TABLE %s ADD CONSTRAINT %s UNIQUE (%s);
";

        return sprintf(
            $pattern,
            $this->quoteIdentifier($index->getTable()->getName()),
            $this->quoteIdentifier($index->getName()),
            $this->getColumnListDDL($index->getColumnObjects()),
        );
    }
}
