<?php

/**
 * MIT License. This file is part of the Propel package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Propel\Generator\Model;
use Propel\Generator\Platform\PlatformInterface;

/**
 * Interface for various ID retrieval method types
 * (i.e. auto-increment, sequence, ID broker, etc.).
 *
 * @author Hans Lellelid <hans@xmpl.org> (Propel)
 * @author Daniel Rall <dlr@collab.net> (Torque)
 */
class IdMethod
{
    /**
     * Key generation via database-specific ID method
     * (i.e. auto-increment for MySQL, sequence for Oracle, etc.).
     *
     * @var string
     */
    public const NATIVE = 'native';

    /**
     * Key based on a sequence
     *
     * @var string
     */
    public const SEQUENCE = 'sequence';

    /**
     * Key type specific to Postgres. 
     *
     * @var string
     */
    public const IDENTITY = 'identity';

    /**
     * Key type specific to Postgres. 
     *
     * @var string
     */
    public const SERIAL = 'serial';

    /**
     * No RDBMS key generation (keys may be generated by the
     * application).
     *
     * @var string
     */
    public const NO_ID_METHOD = 'none';

    /**
     * Get the id method name as defined in this class.
     * 
     * Returns "none" if name cannot be matched.
     * 
     * @param string|null $idMethod
     * @param PlatformInterface|null $platform
     * @return string
     */
    public static function normalizeIdMethodName(?string $idMethod, ?PlatformInterface $platform = null): string
    {
        $lcIdMethod = strtolower($idMethod);
        switch($lcIdMethod)
        {
            case static::IDENTITY:
            case static::SEQUENCE:
            case static::SERIAL:
                return $lcIdMethod;
            case static::NATIVE:
                return ($platform) ? $platform->getNativeIdMethod() : static::NATIVE;
            default:
                return static::NO_ID_METHOD;
        }
    }
}
